version: '3'

services:
    rmq:
        image: rabbitmq:3.8.2-management
        ports: 
            - "5679:5672"
            - "15679:15672"
            - "15699:15692"
    prometheus:
        image: prom/prometheus:v2.14.0
        ports: 
            - "9091:9090"
        volumes: 
            - rabbitmq-prometheus_prometheus:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana:6.5.2
        ports: 
            - "3001:3000"
        volumes: 
            - rabbitmq-prometheus_grafana:/var/lib/grafana
            - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
            - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
            - ./grafana/dashboards:/dashboards

volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana: