{
 "title": "RabbitMQ Overview",
 "time": { "from": "2020-02-05T07:41:09.265Z", "to": "2020-02-05T08:11:09.265Z" },
 "panels": [
  {
   "title": "Ready Messages",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rabbitmq_queue_messages)" }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[1m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rabbitmq_connections)" }
   ]
  },
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers)"
    }
   ]
  },
  {
   "title": "Unack Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked)"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[1m])) +\nsum(rate(rabbitmq_channel_messages_delivered_total[1m])) +\nsum(rate(rabbitmq_channel_messages_delivered_ack_total[1m])) +\nsum(rate(rabbitmq_channel_get_total[1m])) +\nsum(rate(rabbitmq_channel_get_ack_total[1m]))"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rabbitmq_channels)" }
   ]
  },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rabbitmq_queues)" }
   ]
  },
  { "title": "Queued messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Messages ready to be delivered to consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)"
    }
   ]
  },
  {
   "title": "Messages pending consumer acknowledgement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked)"
    }
   ]
  },
  { "title": "Incoming messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages routed to queues / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[1m])"
    }
   ]
  },
  { "title": "Outgoing messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Messages acknowledged / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_acked_total[1m])"
    }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Consumer utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation"
    }
   ]
  },
  { "title": "Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "RMQ Total Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  }
 ]
}